import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from './dummy/views/Header/index'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
     
      <body className={inter.className}>
      <Header/>
      <main className='px-4 py-8 w-full min-h-screen bg-red-50'> {children}</main>
        
        
        </body>
    </html>
  )
}
